### ISSUE TITLE
Integration with HF transformers

### ISSUE THREAD

**Issue by younesbelkada** [Vahe1994/AQLM#11]
Hi there,

Thanks for the great work ! 
We recently added `HfQuantizer` support in HF transformers thanks to @poedator 's work - I was wondering if it would make sense to create a new quantizer `AqlmQuantizer` for this method to natively support inference in HF transformers: https://huggingface.co/docs/transformers/main/en/hf_quantizer 

Let me know if this makes sense!

**Comment by Vahe1994** [comment]
Hello!
Thank you for bringing this up. We will take a look and will try to make this AqlmQuantizer for the method to natively support  inference in HF.

**Comment by younesbelkada** [comment]
Fantastic work @BlackSamorez  !

**Comment by BlackSamorez** [comment]
Now we wait for the release. After that we can merge #14 and close this issue.

**Comment by BlackSamorez** [comment]
Starting with `transformers` `4.38.0`, AQLM is supported through `quantizers` interface.
