### ISSUE TITLE
[Feature Request] Gemma2 support & models

### ISSUE THREAD

**Issue by kristaller486** [Vahe1994/AQLM#111]
Gemma2 is incredible model. With AQLM, it will fit into 12GB GPU.

**Comment by Vahe1994** [comment]
Hello!
Sorry for the late answer. It should fit .I'm planning to get to this soon. I'll keep you updated in this thread, but it may take weeks.

**Comment by kristaller486** [comment]
Thank you for answer. I'll be waiting!

**Comment by igvasilev** [comment]
Will you convert Gemma2 27B as well? Or are there any templates how to do it?
