### ISSUE TITLE
how to get detailed results about the codebooks and codes parameters

### ISSUE THREAD

**Issue by noforit** [Vahe1994/AQLM#115]
Could you please guide me on where to find detailed results about the codebooks and codes parameters for the quantized model ISTA-DASLab/Llama-2-7b-AQLM-2Bit-1x16-hf?

**Comment by Vahe1994** [comment]
Hello @noforit !

If I understand your question, you are asking how to view parameters of codebooks and codes in quantized llayer.
Below is an example of how to do this for the quantized Llama-2-7b-AQLM-2Bit-1x16-hf  for mlp's gate_proj layer in transformer block 0.

```python
quantized_model = AutoModelForCausalLM.from_pretrained(
    "ISTA-DASLab/Llama-2-7b-AQLM-2Bit-1x16-hf",
    torch_dtype="auto", device_map="auto", low_cpu_mem_usage=True,
)
print(quantized_model.model.layers[0].mlp.gate_proj.codes)
print(quantized_model.model.layers[0].mlp.gate_proj.codebooks)
```

If this is not what you were asking, please clarify, and I will try to help.

**Comment by noforit** [comment]
@Vahe1994  Thanks a lot！ Haved solved this issue！
