### ISSUE TITLE
about reproduce PPL

### ISSUE THREAD

**Issue by laomao0** [Vahe1994/AQLM#118]
Hi, I use the codes from AQLM+PVtuning  [https://github.com/Vahe1994/AQLM/tree/pv-tuning]
Following the readme [ 1. Initial model calibration], i use the follwoing setting to reproduce 2x8g8,
However, I get Wikitext2 PPL 14.45,  is it too high?,  is there something to notice for reproduce 2x8g8, and what is the regular PPL for step 1 Initial model calibration using 2x8g8?

settings:
export MODEL_PATH=/Llama-2-7b-hf/
export DATASET_PATH=pajama
export MODEL_SEQLEN=4096   
export NBITS_PER_CODEBOOK=8
export GROUP_SIZE=8
export BLOCKWISE_FINETUNE_EPOCHS=25
export CUDA_VISIBLE_DEVICES=6,7   # or e.g. 0,1,2,3
export SAVE_PATH=/output_2x8g8/
export WANDB_PROJECT=wandb_output
export WANDB_NAME=wandb_llama2_2x8

python main.py \
    $MODEL_PATH \
    $DATASET_PATH \
    --nsamples=2048 \
    --val_size=256 \
    --model_seqlen=4096 \
    --num_codebooks=2 \
    --nbits_per_codebook=$NBITS_PER_CODEBOOK \
    --out_group_size=1 \
    --in_group_size=$GROUP_SIZE \
    --beam_size=1 \
    --relative_mse_tolerance=0.01 \
    --max_epochs=100 \
    --finetune_lr=1e-4 \
    --finetune_adam_beta1=0.90 \
    --finetune_adam_beta2=0.999 \
    --finetune_keep_best \
    --finetune_batch_size=64 \
    --local_batch_size=4 \
    --finetune_max_epochs=$BLOCKWISE_FINETUNE_EPOCHS \
    --finetune_early_stop=3 \
    --save $SAVE_PATH \
    --resume
    --offload_activations \

**Comment by galqiwi** [comment]
Hi! I see that you use `NBITS_PER_CODEBOOK=8`. We [advise](https://github.com/Vahe1994/AQLM/blob/pv-tuning/README.md) you to use `NBITS_PER_CODEBOOK=16` value. We think that it is the reason for your suboptimal results.

**Comment by galqiwi** [comment]
Hi! We believe the reason for your high perplexity is `beam_size` parameter. While it is optimal to use beam_size=1 for 1x16 quantization, we advise using beam_size=8 (beam_size=4 can be fine too if beam_size=8 is too slow).

**Comment by laomao0** [comment]
Hi, I re-train for 2x8g8 and 1x16g8，
PPL for 2x8g8 is  8.3755(wiki)  10.3067(c4)
PPL for 1x16g8 is 6.3194(wiki) 8.12(c4)

beam_size for 1x16g8 is 1, I think the reproduced PPL is reasonable.
beam_size for 2x8g8 is 1, I will try beam_size=4 for 2x8g8.

Thanks for your comments.

**Comment by laomao0** [comment]
I have trained the beam_size=4 for 2x8g8 [the same script, except beam_size=4].
however the PPL for wiki is 9.0859, c4 is 

I want to know the setting of [[1. Initial model calibration](https://github.com/Vahe1994/AQLM/tree/pv-tuning)] to quantize ISTA-DASLab/Llama-2-7b-AQLM-2Bit-2x8-hf. And is PPL=8.37(beam_size=1) or 9.09(beam_size=4) correct?

**Comment by Vahe1994** [comment]
Hi,  @laomao0 !
To be frank, both ppl seems a little bit high.


I got 7.61 on WIki2 without global fine-tuning with these parameters. 

```bash
MODEL_PATH=$INPUT_PATH/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9
DATASET_PATH=red_pajama_n=4096_4096_context_length.pth
 
python main.py \
    $MODEL_PATH \
    $DATASET_PATH \
    --nsamples=2048 \
    --val_size=256 \
    --model_seqlen=4096 \
    --num_codebooks=2 \
    --nbits_per_codebook=8 \
    --out_group_size=1 \
    --in_group_size=8 \
    --beam_size=1 \
    --relative_mse_tolerance=0.01 \
    --max_epochs=100 \
    --finetune_lr=3e-5 \
    --finetune_adam_beta1=0.90 \
    --finetune_adam_beta2=0.95 \
    --finetune_keep_best \
    --finetune_batch_size=64 \
    --local_batch_size=4 \
    --finetune_max_epochs=25 \
    --finetune_early_stop=3 \
    --offload_activations \
    --save $SNAPSHOT_PATH \
    --resume \
    --wandb 
```
The quantization was performed using 2 A100.  Usually when increasing beam size it lead to better ppl. So it is recommended to use beam_size=8 (here I accidentally used beam_size=1). 
p.s. red_pajama_n=4096_4096_context_length.pth - is just a slice of red_pajama dataset.


After quantization, you can perform global fine-tuning to further improve quality. In the AQLM paper it was done with the setup below: 

```bash 
MODEL_PATH=$INPUT_PATH/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9
DATASET_PATH=red_pajama_n=4096_4096_context_length.pth

python finetune.py \
  --base_model $MODEL_PATH \
  --quant_model $INPUT_PATH \
  --dataset $DATASET_PATH \
  --model_seqlen=4096 \
  --eval_model_seqlen=4096 \
  --eval_datasets wikitext2 \
  --nsamples=4096 \
  --val_size=128 \
  --lr=1e-5 \
  --adam_beta1=0.90 \
  --adam_beta2=0.999 \
  --epochs=2 \
  --early_stop=3 \
  --batch_size=16 \
  --microbatch_size=1 \
  --save $DATA_PATH \
  --gradient_checkpointing \
  --amp \
  --wandb \
  --device_map auto
```

It was fine-tuned using 4 A100. With the global fine-tuning I got ppl on wikitext2 6.57. Both numbers where reported in the Table 9 of AQLM paper(see Appendix). I used code from here  https://github.com/Vahe1994/AQLM/tree/AQLM_camera_ready

Using PV-Tuning should give you better results.

Hope this helps.

**Comment by laomao0** [comment]
thanks your comments, it helps a lot.
