### ISSUE TITLE
GPU OUT OF MEMORY

### ISSUE THREAD

**Issue by LiMa-cas** [Vahe1994/AQLM#121]
![image](https://github.com/user-attachments/assets/7a8e2b8a-3b61-49f8-8602-e579963850df)

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 GiB. GPU 0 has a total capacity of 47.54 GiB of which 9.50 GiB is free. Process 1509125 has 9.68 GiB memory in use. Including non-PyTorch memory, this process has 28.30 GiB memory in use. Of the allocated memory 28.00 GiB is allocated by PyTorch, and 1.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

I think the GPU has enough memory since I used the 
![image](https://github.com/user-attachments/assets/c53744e9-c170-47a9-9352-046f9e876526)

**Comment by Vahe1994** [comment]
Hi @LiMa-cas,

Could you please share more information? Specifically:

1.The script/code you ran: Which version of the code did you use?
2. Which model did you use?
3. When did this happen? Which part of the code?(you can just share logs)
4. Were there any other processes running on that device?

**Comment by LiMa-cas** [comment]
Hi，thanks for response.
1.I download from this code: https://github.com/Vahe1994/AQLM
2.I use the model - Meta-llama3-8b-instruct
3.It happend when：
![image](https://github.com/user-attachments/assets/1638f4e7-ecb7-40c8-8514-8e3621de9cfe)
4.the GPU used is as following，but I think it seemed has enough space...
![image](https://github.com/user-attachments/assets/e78e7523-4631-4a39-9f2a-c72a4a9edf2d)

**Comment by LiMa-cas** [comment]
Hi，problems solved with using 80GB

**Comment by LiMa-cas** [comment]
Hi，another question，if I want to quantization for 4 bit， is the following parameters right？( --scale_nbits=4 )
python main.py $MODEL_PATH $DATASET_PATH \
 --nsamples=1024 \
 --val_size=128 \
 --num_codebooks=1 \
 --nbits_per_codebook=16 \
 --in_group_size=8 \
 --relative_mse_tolerance=0.01 \
 --finetune_batch_size=32 \
 --finetune_max_epochs=10 \
 --finetune_early_stop=3 \
 --finetune_keep_best \
 --local_batch_size=1 \
 --scale_nbits=4 \
 --resume \
 --save $SAVE_PATH

**Comment by Vahe1994** [comment]
Hi, @LiMa-cas!  
To get `avg_bits` around 4, as an example, you can use the following command:

```bash
python main.py $MODEL_PATH $DATASET_PATH \
--nsamples=2048 \
--val_size=128 \
--num_codebooks=2 \
--nbits_per_codebook=16 \
--in_group_size=8 \
--relative_mse_tolerance=0.01 \
--finetune_batch_size=32 \
--finetune_max_epochs=10 \
--finetune_early_stop=3 \
--finetune_keep_best \
--local_batch_size=1 \
--offload_activations \
--resume \
--save $SAVE_PATH
```

You can also use `--nsamples=1024` if you prefer. Use `--offload_activations` to offload activations for reduced VRAM usage.  If block fine-tuning takes a lot of time please reduce `--finetune_max_epochs` and `--finetune_early_stop`.
This command will give you quantized model without global fine-tuning. If you farther improve model quality use global fine-tuning, although for 4 bits I'm not sure how much it will improve. 

P.s. The `--scale_nbits` parameter controls group-wise scales. In all our experiments, its value is set to 0, meaning group-wise scales are not used. Instead, row-wise scales are applied. For more details, see [this link](https://github.com/Vahe1994/AQLM/blob/a441a3f0ece4cbaa2a91a3421c95a8b7432e4d99/main.py#L693).

If you have any further question please ask.

**Comment by LiMa-cas** [comment]
Hi，thanks a lot. There are 2 script called "finetune.py". U mean "global fine-tuning",  is this the one called "finetune.py" as follows?
![image](https://github.com/user-attachments/assets/2f100a37-a132-4646-bf99-d863530ce19a)
but main.py above using the "finetune.py" under src:
![image](https://github.com/user-attachments/assets/4d1ef224-3f02-49d5-91f2-f1a1c852c691)


There are problems when I use the first one "finetune.py" (I am nor sure is the right one) to finetuned the LLama3-AWQ, I need to
set other parameters:
![image](https://github.com/user-attachments/assets/5b62d958-1cac-47c4-8512-7e491104693d)


Therefore, I list all of my questions:
1. the fine-tuning method is global finetuning of the first one, anther is block fine-tuing methods which used in main.py? could it is possible I used it all in AWQ method?
2. after setting the parameters above, I have the problems:
![image](https://github.com/user-attachments/assets/a88e4d02-bfdc-479a-8f2a-80f1532bc17f)

**Comment by Vahe1994** [comment]
Hi, @LiMa-cas !

Sorry for the late response. AQLM, when quantizing by default, uses block fine-tuning, as you correctly mentioned from the `src/finetuning.py` file. Global fine-tuning is handled in the `finetune.py` file, located above `main.py`.

An example of how to perform global  fine-tuning can be found in the README: see [README](https://github.com/Vahe1994/AQLM?tab=readme-ov-file#finetuning). For more details what it does, please refer to the paper: [https://arxiv.org/abs/2405.14852](https://arxiv.org/abs/2405.14852).

Let me try to answer your questions:

1. Yes, that is correct. PV-Tuning can technically be used for AWQ, but in the current code, this has not been implemented and was not tested.
2. If you are using PV-Tuning with AWQ quantization, this may happen. If you are encountering this error while using global fine-tuning on AQLM-quantized weights, please let me know. I will try to figure out what went wrong.

Hope this helps.

**Comment by LiMa-cas** [comment]
Thanks a lot. So global fine-tuning is not good for 4-bit quantization? could I use the finetuning in AQLM for AWQ 4-bit quantization and get a good results?

**Comment by Vahe1994** [comment]
@LiMa-cas global fine-tuning is good, but not as effective as 2-bit quantization. At least it is true in AQLM case. 
As I mentioned above, technically, you can use global fine-tuning to improve AWQ. However, you would need to adjust the code to make it work with AWQ. Currently, we don't have the code to support this, and we haven't tested it. So, I don't have a definite answer as to whether it's possible or if it would improve AWQ. Sorry about this.

**Comment by LiMa-cas** [comment]
Ok，thanks very much！
