### ISSUE TITLE
A small error in the article

### ISSUE THREAD

**Issue by ArtemBiliksin** [Vahe1994/AQLM#122]
Hello! 

There is a small error in the article (v3) in appendix H. The number of bits for the codes will be $d_{out} \cdot (d_{in} / g) \cdot B \cdot M$ instead of $d_{out} \cdot (d_{in} / g) \cdot B$. This change should go into the formula for $\bar{b}$:

$$
\bar{b} = \frac{size\ in\ bits}{number\ of\ parameters} =
\frac{16 \cdot g \cdot M \cdot 2^B + d_{out} \cdot(d_{in}/g) \cdot B \cdot \overbrace{M}^{\downarrow}+ 16 \cdot d_{out}}{d_{out}\cdot d_{in}}
$$

I reproduced the example from the article to calculate the bits per parameter for the LLAMA 2 70B model using the original formula. I did not get a value of 2.002. I got 1.002. I added the multiplier M as I wrote above and got 2.002.
![Снимок экрана от 2024-09-05 17-36-44](https://github.com/user-attachments/assets/3d6bba8e-c75c-4fea-95ae-d78ddbc5fd89)

The M multiplier is written about in section 3.1. Overview before formula (3): "The resulting scheme encodes each
group of $g$ weights using $M \cdot B$ bits ...”. The number of groups is equal to $d_{out} \cdot (d_{in} / g)$. Therefore, the total number of bits for the codes is equal to $d_{out} \cdot (d_{in} / g) \cdot M \cdot B$.

**Comment by Vahe1994** [comment]
Hi, @ArtemBiliksin!
Yes, you are correct. Thank you for noticing this! We will correct this in the revision.
