### ISSUE TITLE
The pseudo-algorithm contains an error

### ISSUE THREAD

**Issue by ArtemBiliksin** [Vahe1994/AQLM#123]
Hello!

The pseudo-algorithm (Algorithm 1 AQLM: Additive Quantization for LLMs) from the paper (v3) contains an error in line **21**. Instead of
```
21: Y_block := block(X_block)
```
should be
```
21: X_block := block(X_block)
```

You can't use the option
```
21: Y_block := block(X_block)
```
because line number **4**
```
4: Y_block := block(X_block)
```
will **override** the value of Y_block on the new iteration by i.

You need to use 
```
21: X_block := block(X_block)
```
because this variant is used in main.py (master, a441a3f). In lines [319-325](https://github.com/Vahe1994/AQLM/blob/main/main.py#L319-L325), the outs variable is changed by reference. In line [344](https://github.com/Vahe1994/AQLM/blob/main/main.py#L344) `inps = outs`, that is, `X_block = block(X_block)`.

**Comment by Vahe1994** [comment]
Hi, @ArtemBiliksin!
Thank you again for your careful reading of the paper. You are correct; there was a misspelling in the text. We will correct this in the new revision.
