### ISSUE TITLE
how to use in ollama?

### ISSUE THREAD

**Issue by NeverBeLazyG** [Vahe1994/AQLM#131]
hello,

how can i use this models in ollama, can you give me some tutorial link or somthing ?

thank you

**Comment by BlackSamorez** [comment]
Hi! AQLM only works with [transformers](https://huggingface.co/docs/transformers/main/en/quantization/aqlm) and [vLLM](https://docs.vllm.ai/en/v0.6.0/getting_started/examples/aqlm_example.html). No ollama support (and no such plans).

**Comment by NeverBeLazyG** [comment]
really bad. thank you
