### ISSUE TITLE
[Question] the parameters of finetune.py 

### ISSUE THREAD

**Issue by noforit** [Vahe1994/AQLM#137]
If I want to reproduce the quantization process of LLaMA2-7B mentioned in the paper, especially during the end-to-end fine-tuning process, how should the parameters of finetune.py be set, such as block_type？ Thanks
```
finetune.py: error: the following arguments are required:  --block_type
```
```
python finetune.py \
  --base_model $MODEL_PATH \
  --quant_model $INPUT_PATH \
  --dataset $DATASET_PATH \
  --nsamples=<TOTAL_SIZE> \
  --val_size=<VAL_SIZE> \
  --lr=1e-5 \
  --adam_beta1=0.90 \
  --adam_beta2=0.999 \
  --epochs=5 \
  --early_stop=3 \
  --batch_size=8 \
  --microbatch_size=4 \
  --save $DATA_PATH \
  --gradient_checkpointing
```

![image](https://github.com/user-attachments/assets/0ea3841f-1459-4ac0-8f57-8970474f8e7a)
There are many differences between the command-line parameters and the parameters in finetune.py, may correct them

**Comment by noforit** [comment]
And what the data path should i use？
![image](https://github.com/user-attachments/assets/e23d99b8-0638-4a3a-9597-9182cc0f89f7)

**Comment by ArtemBiliksin** [comment]
Hello, @noforit ! In your case, `block_type` should be equal to `LlamaDecoderLayer` ([see example in issue 98](https://github.com/Vahe1994/AQLM/issues/98#issuecomment-2158750539), `export BLOCK_CLASS_NAME=LlamaDecoderLayer`).

**Comment by ArtemBiliksin** [comment]
> And what the data path should i use？ ![image](https://private-user-images.githubusercontent.com/97608046/379267303-e23d99b8-0638-4a3a-9597-9182cc0f89f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNDk1MzUsIm5iZiI6MTczMDA0OTIzNSwicGF0aCI6Ii85NzYwODA0Ni8zNzkyNjczMDMtZTIzZDk5YjgtMDYzOC00YTNhLTk1OTctOTE4MmNjMGY4OWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDE3MTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMTc4MjljZjk3ZWE3NzRjNzlmMTU5MTU2YWE0YTg3YTdlYjFhMjQyOTcwODdlYzc2NTcyYzI0MzhjODFlMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B5S5aY43afK-pFAKBYDtgs-a_Cvv2ndyvrQjxbLKBrY)

Please print out the `ls /home/jishiyu/quantization/AQLM_origin/data/data` command. So that I can answer you more accurately.

**Comment by noforit** [comment]
Hi! @Vahe1994 @ArtemBiliksin 
Thank you for your response and help. I have found the specific parameter values and was able to reproduce the results at https://github.com/Vahe1994/AQLM/issues/118. 
But I noticed that after the commit at https://github.com/Vahe1994/AQLM/commit/a441a3f0ece4cbaa2a91a3421c95a8b7432e4d99, 
the code for PV tuning was merged into finetune.py, but the example in the README for the [finetune script](https://github.com/Vahe1994/AQLM?tab=readme-ov-file#finetuning) has not been updated. This led to the issues I mentioned above. I hope you can update the README accordingly. Thanks a lot！

**Comment by galqiwi** [comment]
@noforit, thanks for poing out the error in the README, we will fix it.
Did I understand correctly that
1) You found old finetuning script
2) This script is what you were looking for, not the PV-tuning version

**Comment by noforit** [comment]
@galqiwi Yes, I have no other questions. Thank you very much!
