### ISSUE TITLE
[Question] Influence of calibration data on quantization of instructive models

### ISSUE THREAD

**Issue by ArtemBiliksin** [Vahe1994/AQLM#141]
Hello! 

I have a question about the quantization stage of the AQLM method. How much redpajama-type data (non-instructive data) can affect quantization of instructive models that use [chat-templates](https://huggingface.co/docs/transformers/main/en/chat_templating#what-does-continuefinalmessage-do) in training? 

I realize that I can't easily apply AQLM on instructive data, the current code doesn't support it. Maybe I don't need to do quantization on chat data at all and make do with non-instructive data, i.e. use redpajama data, for example. And use instructive data at the stage of end-to-end finetuning.

**Comment by Godofnothing** [comment]
Hi, @ArtemBiliksin . 
The study on the impact of calibration data is the thing I am currently working on.
What I can say is that cosmopedia/fineweb_edu appears to be slightly but consistently better on 0-shot benchmarks and MMLU 5-shot than RedPajama/C4/Wikitext2. 

Have not evaluated so far impact of chat template in calibration data.
My intuition is that the calibration data should resemble the inference case. 
However, the specifi details may be less important compared to fine-tuning case.

**Comment by ArtemBiliksin** [comment]
Hi. @Godofnothing ! Thanks for the reply!
