### ISSUE TITLE
Tokenizer

### ISSUE THREAD

**Issue by terarachang** [Vahe1994/AQLM#144]
Hi! Thanks for releasing the repo! I have a question about the tokenizer.
I load the tokenizer with `tokenizer = AutoTokenizer.from_pretrained('ISTA-DASLab/Meta-Llama-3-8B-Instruct-AQLM-2Bit-1x16')`. It seems to me that this tokenizer encodes the sentence the same way as `meta-llama/Meta-Llama-3-8B-Instruct`, except that your tokenizer does not prepend the sentence with the bos_token? (I did `tokenizer(sentence, add_special_tokens=True)['input_ids']` to check this)
- I wonder if there are other differences I'm not aware of.
- Also, should we not use the bos_token for generation?

**Comment by galqiwi** [comment]
Thank you for noticing and opening this issue! I just updated `ISTA-DASLab/Meta-Llama-3-8B-Instruct-AQLM-2Bit-1x16` tokenizer, now it is the same as the one in `meta-llama/Meta-Llama-3-8B-Instruct`. 

Please, confirm that we resolved the issue

**Comment by terarachang** [comment]
Thank you!
