### ISSUE TITLE
Unable to reproduce Llama 3 8b perplexity

### ISSUE THREAD

**Issue by HighSpeeds** [Vahe1994/AQLM#152]
When I run the fp16 Llama-3 8b model using the evaluation framework provided I am unable to reproduce the perplexities reported in the PV-tuning paper. I get a perplexity of **5.7559** for Wikitext2 (reported **5.54**) and a perplexity of **8.3228** (reported **7.10**). The command I used was:

```
export CUDA_VISIBLE_DEVICES=0
python main.py meta-llama/Meta-Llama-3-70B c4 --no_quant
```
And I added one 2 lines in main.py after lines 892, to put the model onto the device
```
else:
    model.to(args.devices[0])
```
I created a new conda enviroment and installed the packages per requirements.txt. Is there something I am missing to be able to reproduce the fp16 perplexities?

**Comment by galqiwi** [comment]
Default model_seqlen argument is 4096. For Llama3-8b we used 8192. Try running eval command like this:
```
python main.py meta-llama/Meta-Llama-3-70B c4 --no_quant --model_seqlen 8192
```
