### ISSUE TITLE
benchmark/matmul_benchmark.py  Running Error

### ISSUE THREAD

**Issue by KellyGong** [Vahe1994/AQLM#161]
Hello! When I running the benchmark file ``matmul_benchmark.py``, It produces the error in the line 105: 
```
matmul = CUDA_KERNEL.code1x16_matmat if args.nbits_per_codebook == 16 else CUDA_KERNEL.code2x8_matmat

output = matmul(input, codes, codebooks, scales)
```

with the error 
```
TypeError: code1x16_matmat(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: Optional[torch.Tensor]) -> torch.Tensor
```

For each argument, I follow your codes and set the ``input, codebooks and scales`` to ``torch.half`` and ``codes`` to ``torch.int16``.

Could you give me some suggestions to fix this bug in my devices? Thanks a lot!

My environments are NVIDIA A6000 and Pytorch 2.3.0+cu121

**Comment by BlackSamorez** [comment]
Hi! We haven't used or updated the layer-wise benchmarks code in quite a while. Instead now we mostly report and refer people to e2e `tok/s` benchmarks via the [vLLM integration](https://docs.vllm.ai/en/stable/getting_started/examples/aqlm_example.html).
Nevertheless, I'll take a look at what can be done here...

**Comment by KellyGong** [comment]
Thank you for paying your valuable time on my issue! Since I hope to apply your great works to other research areas, not limited to LLM, knowing how the basic implementation and running procedure would be more helpful for me.

**Comment by BlackSamorez** [comment]
@KellyGong I pushed a 1-line fix
