### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by l33tx0** [Vahe1994/AQLM#18]
py -m pip install aqlm[gpu,cpu]
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting aqlm[cpu,gpu]
  Downloading aqlm-1.0.0-py3-none-any.whl (10 kB)
Collecting torch>=2.1.1
  Downloading torch-2.2.0-cp311-cp311-win_amd64.whl (198.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.6/198.6 MB 12.6 MB/s eta 0:00:00
Collecting transformers==4.37.0
  Downloading transformers-4.37.0-py3-none-any.whl (8.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 8.5 MB/s eta 0:00:00
Collecting numba>=0.56.4
  Downloading numba-0.59.0-cp311-cp311-win_amd64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 18.7 MB/s eta 0:00:00
Collecting scipy>=1.11.3
  Downloading scipy-1.12.0-cp311-cp311-win_amd64.whl (46.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 13.1 MB/s eta 0:00:00
ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 0.55.0 Requires-Python >=3.7,<3.11; 0.55.0rc1 Requires-Python >=3.7,<3.11; 0.55.1 Requires-Python >=3.7,<3.11; 0.55.2 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement triton>=2.1; extra == "gpu" (from aqlm[cpu,gpu]) (from versions: none)
ERROR: No matching distribution found for triton>=2.1; extra == "gpu"

**Comment by Godofnothing** [comment]
Hi, @l33tx0. Could you, please, provide more information about your environment? Seems like your Python version is either too new or too old.

**Comment by justheuristic** [comment]
If you're running on CPU-only machine (i.e. no GPU), you may be able to simply comment-out the triton imports in the code and use the CPU kernel.

**Comment by BlackSamorez** [comment]
> If you're running on CPU-only machine (i.e. no GPU), you may be able to simply comment-out the triton imports in the code and use the CPU kernel.

That would mean simply installing with `aqlm[cpu]`.

**Comment by joevenzon** [comment]
Here are the steps I had to take to get aqlm installed on windows in oobabooga text-generation-webui:

- install visual studio 2022
- make sure cl.exe was in my windows path
- from the oobabooga cmd_windows prompt, pip install --no-deps aqlm[gpu]
- find your pip location via pip show aqlm, go into the aqlm/inference_kernels folder, and modify cuda_kernel.cpp by adding the __restrict keyword to all of the _cuda functions' pointer arguments
