### ISSUE TITLE
RuntimeError: Unknown layout

### ISSUE THREAD

**Issue by sankeerth43** [Vahe1994/AQLM#20]
Hi, I've been encountering this problem when running this [notebook](https://colab.research.google.com/drive/1-xZmBRXT5Fm3Ghn4Mwa2KRypORXb855X?usp=sharing#scrollTo=ZDOtpnJGizsx) on local machine with an L4. I've followed the instructions from the notebook on `Python3.10`. 

```
Name: torch
Version: 2.2.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/ubuntu/anaconda3/envs/aqlm/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, aqlm, torchaudio, torchvision

```
```
  +---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                       On | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0               33W /  75W|  13858MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     16482      C   ...untu/anaconda3/envs/aqlm/bin/python    13856MiB |
+---------------------------------------------------------------------------------------+

```
> The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
>   Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
>   ---------------------------------------------------------------------------
>   RuntimeError                              Traceback (most recent call last)
>   Cell In[3], line 1
>   ----> 1 output = quantized_model.generate(tokenizer("", return_tensors="pt")["input_ids"].cuda(), max_new_tokens=10)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
>       112 @functools.wraps(func)
>       113 def decorate_context(*args, **kwargs):
>       114     with ctx_factory():
>   --> 115         return func(*args, **kwargs)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/transformers/generation/utils.py:1513, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
>      1496     return self.assisted_decoding(
>      1497         input_ids,
>      1498         candidate_generator=candidate_generator,
>      (...)
>      1509         **model_kwargs,
>      1510     )
>      1511 if generation_mode == GenerationMode.GREEDY_SEARCH:
>      1512     # 11. run greedy search
>   -> 1513     return self.greedy_search(
>      1514         input_ids,
>      1515         logits_processor=prepared_logits_processor,
>      1516         stopping_criteria=prepared_stopping_criteria,
>      1517         pad_token_id=generation_config.pad_token_id,
>      1518         eos_token_id=generation_config.eos_token_id,
>      1519         output_scores=generation_config.output_scores,
>      1520         return_dict_in_generate=generation_config.return_dict_in_generate,
>      1521         synced_gpus=synced_gpus,
>      1522         streamer=streamer,
>      1523         **model_kwargs,
>      1524     )
>      1526 elif generation_mode == GenerationMode.CONTRASTIVE_SEARCH:
>      1527     if not model_kwargs["use_cache"]:
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/transformers/generation/utils.py:2350, in GenerationMixin.greedy_search(self, input_ids, logits_processor, stopping_criteria, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, streamer, **model_kwargs)
>      2347 model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
>      2349 # forward pass to get next token
>   -> 2350 outputs = self(
>      2351     **model_inputs,
>      2352     return_dict=True,
>      2353     output_attentions=output_attentions,
>      2354     output_hidden_states=output_hidden_states,
>      2355 )
>      2357 if synced_gpus and this_peer_finished:
>      2358     continue  # don't waste resources running the code we don't need
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
>      1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
>      1510 else:
>   -> 1511     return self._call_impl(*args, **kwargs)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1520, in Module._call_impl(self, *args, **kwargs)
>      1515 # If we don't have any hooks, we want to skip the rest of the logic in
>      1516 # this function, and just call forward.
>      1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>      1518         or _global_backward_pre_hooks or _global_backward_hooks
>      1519         or _global_forward_hooks or _global_forward_pre_hooks):
>   -> 1520     return forward_call(*args, **kwargs)
>      1522 try:
>      1523     result = None
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py:1360, in MixtralForCausalLM.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, output_router_logits, return_dict)
>      1357 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
>      1359 # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
>   -> 1360 outputs = self.model(
>      1361     input_ids=input_ids,
>      1362     attention_mask=attention_mask,
>      1363     position_ids=position_ids,
>      1364     past_key_values=past_key_values,
>      1365     inputs_embeds=inputs_embeds,
>      1366     use_cache=use_cache,
>      1367     output_attentions=output_attentions,
>      1368     output_hidden_states=output_hidden_states,
>      1369     output_router_logits=output_router_logits,
>      1370     return_dict=return_dict,
>      1371 )
>      1373 hidden_states = outputs[0]
>      1374 logits = self.lm_head(hidden_states)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
>      1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
>      1510 else:
>   -> 1511     return self._call_impl(*args, **kwargs)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1520, in Module._call_impl(self, *args, **kwargs)
>      1515 # If we don't have any hooks, we want to skip the rest of the logic in
>      1516 # this function, and just call forward.
>      1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>      1518         or _global_backward_pre_hooks or _global_backward_hooks
>      1519         or _global_forward_hooks or _global_forward_pre_hooks):
>   -> 1520     return forward_call(*args, **kwargs)
>      1522 try:
>      1523     result = None
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py:1228, in MixtralModel.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, use_cache, output_attentions, output_hidden_states, output_router_logits, return_dict)
>      1217     layer_outputs = self._gradient_checkpointing_func(
>      1218         decoder_layer.__call__,
>      1219         hidden_states,
>      (...)
>      1225         use_cache,
>      1226     )
>      1227 else:
>   -> 1228     layer_outputs = decoder_layer(
>      1229         hidden_states,
>      1230         attention_mask=attention_mask,
>      1231         position_ids=position_ids,
>      1232         past_key_value=past_key_values,
>      1233         output_attentions=output_attentions,
>      1234         output_router_logits=output_router_logits,
>      1235         use_cache=use_cache,
>      1236     )
>      1238 hidden_states = layer_outputs[0]
>      1240 if use_cache:
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
>      1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
>      1510 else:
>   -> 1511     return self._call_impl(*args, **kwargs)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1520, in Module._call_impl(self, *args, **kwargs)
>      1515 # If we don't have any hooks, we want to skip the rest of the logic in
>      1516 # this function, and just call forward.
>      1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>      1518         or _global_backward_pre_hooks or _global_backward_hooks
>      1519         or _global_forward_hooks or _global_forward_pre_hooks):
>   -> 1520     return forward_call(*args, **kwargs)
>      1522 try:
>      1523     result = None
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py:934, in MixtralDecoderLayer.forward(self, hidden_states, attention_mask, position_ids, past_key_value, output_attentions, output_router_logits, use_cache, **kwargs)
>       931 hidden_states = self.input_layernorm(hidden_states)
>       933 # Self Attention
>   --> 934 hidden_states, self_attn_weights, present_key_value = self.self_attn(
>       935     hidden_states=hidden_states,
>       936     attention_mask=attention_mask,
>       937     position_ids=position_ids,
>       938     past_key_value=past_key_value,
>       939     output_attentions=output_attentions,
>       940     use_cache=use_cache,
>       941 )
>       942 hidden_states = residual + hidden_states
>       944 # Fully Connected
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
>      1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
>      1510 else:
>   -> 1511     return self._call_impl(*args, **kwargs)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1520, in Module._call_impl(self, *args, **kwargs)
>      1515 # If we don't have any hooks, we want to skip the rest of the logic in
>      1516 # this function, and just call forward.
>      1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>      1518         or _global_backward_pre_hooks or _global_backward_hooks
>      1519         or _global_forward_hooks or _global_forward_pre_hooks):
>   -> 1520     return forward_call(*args, **kwargs)
>      1522 try:
>      1523     result = None
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py:730, in MixtralSdpaAttention.forward(self, hidden_states, attention_mask, position_ids, past_key_value, output_attentions, use_cache)
>       719     return super().forward(
>       720         hidden_states=hidden_states,
>       721         attention_mask=attention_mask,
>      (...)
>       725         use_cache=use_cache,
>       726     )
>       728 bsz, q_len, _ = hidden_states.size()
>   --> 730 query_states = self.q_proj(hidden_states)
>       731 key_states = self.k_proj(hidden_states)
>       732 value_states = self.v_proj(hidden_states)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1511, in Module._wrapped_call_impl(self, *args, **kwargs)
>      1509     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
>      1510 else:
>   -> 1511     return self._call_impl(*args, **kwargs)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py:1520, in Module._call_impl(self, *args, **kwargs)
>      1515 # If we don't have any hooks, we want to skip the rest of the logic in
>      1516 # this function, and just call forward.
>      1517 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>      1518         or _global_backward_pre_hooks or _global_backward_hooks
>      1519         or _global_forward_hooks or _global_forward_pre_hooks):
>   -> 1520     return forward_call(*args, **kwargs)
>      1522 try:
>      1523     result = None
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/aqlm/inference.py:65, in QuantizedLinear.forward(self, input)
>        59 if (
>        60     not input.is_cuda
>        61     and self.codebook_size == 256
>        62     and self.codes.shape[0] == self.out_features // self.out_group_size
>        63 ):
>        64     self.codes.data = torch.permute(self.codes.data, (1, 0, 2)).contiguous()  #  TODO: fix this thing
>   ---> 65 return forward_pass_quantized_linear(input, self.codes, self.codebooks, self.scales, self.bias)
>   
>   File ~/anaconda3/envs/aqlm/lib/python3.10/site-packages/aqlm/inference_kernels/kernel_selector.py:24, in forward_pass_quantized_linear(input, codes, codebooks, scales, bias)
>        19     from .cuda_kernel import CUDA_KERNEL
>        21     assert (
>        22         input.dtype == torch.float16
>        23     ), f"please load the model with `torch_dtype=torch.float16`, as {input.dtype} is not supported on GPU yet"
>   ---> 24     return CUDA_KERNEL.code1x16_matmat(input, codes, codebooks, scales) + (bias if bias is not None else 0)
>        25 case (True, 2, 256, 1, 8):
>        26     from .cuda_kernel import CUDA_KERNEL
>   
>   RuntimeError: Unknown layout
>

**Comment by sankeerth43** [comment]
```
import os
from typing import Optional
​
import torch
from torch.utils.cpp_extension import load
​
​
CUDA_FOLDER = "/home/ubuntu/anaconda3/envs/aqlm/lib/python3.10/site-packages/aqlm/inference_kernels/"
CUDA_KERNEL = load(
    name="codebook_cuda",
    sources=[os.path.join(CUDA_FOLDER, "cuda_kernel.cpp"), os.path.join(CUDA_FOLDER, "cuda_kernel.cu")],
)
torch.library.define(
    "aqlm::code1x16_matmat", "(Tensor input, Tensor codes, Tensor codebooks, Tensor scales, Tensor bias) -> Tensor"
)
​
torch.library.impl("aqlm::code1x16_matmat", "default", CUDA_KERNEL.code1x16_matmat)
@torch.library.impl_abstract("aqlm::code1x16_matmat")
def code1x16_matmat_meta(input, codes, codebooks, scales, bias):
    return torch.empty(input.shape[:-1] + (codes.shape[0],), device=input.device, dtype=input.dtype)
inputs = torch.zeros([1, 2, 4096], dtype=torch.float16).cuda()
codes = torch.zeros([4096, 512, 1], dtype=torch.float16).cuda()
codebooks = torch.zeros([1, 65536, 1, 8], dtype=torch.float16).cuda()
scales = torch.zeros([4096, 1, 1, 1], dtype=torch.float16).cuda()
bias = None
inputs = inputs.contiguous()
codes = codes.contiguous()
codebooks = codebooks.contiguous()
scales = scales.contiguous()
if bias is not None:
    bias = bias.contiguous()
​
CUDA_KERNEL.code1x16_matmat(inputs, codes, codebooks, scales, bias)

```

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Cell In[13], line 1
> ----> 1 CUDA_KERNEL.code1x16_matmat(inputs, codes, codebooks, scales, bias)
> 
> RuntimeError: Unknown layout
> 

I've run the same code by forcing triton kernel and it is working fine. I wanted to know If i'm doing something wrong.

**Comment by BlackSamorez** [comment]
Hi @sankeerth43 ! 
I don't think you're doing anything wrong. We're honestly not sure where this problem originates from. We don't have access to any Nvidia L4 GPUs to try and reproduce the error either. One thing you could do is delete the torch compiled kernels cache (usually `~/.cache/torch_extensions`), update the `aqlm` library (`pip install --upgrade aqlm`) and maybe check that the compiler for CUDA compilation is sourced correctly `which nvcc`. Other than that, I'm not sure. We're trying to identify the error as well.

**Comment by Cory-M** [comment]
> Hi @sankeerth43 ! I don't think you're doing anything wrong. We're honestly not sure where this problem originates from. We don't have access to any Nvidia L4 GPUs to try and reproduce the error either. One thing you could do is delete the torch compiled kernels cache (usually `~/.cache/torch_extensions`), update the `aqlm` library (`pip install --upgrade aqlm`) and maybe check that the compiler for CUDA compilation is sourced correctly `which nvcc`. Other than that, I'm not sure. We're trying to identify the error as well.

thanks!
turns out it's an issue with the newest pytorch 2.2.0. Capping pytorch==2.1.0 solved this for me.

**Comment by Cory-M** [comment]
> Any progress on this? I'd like to try this project, but it's proving extremely difficult

as i mentioned above, cap the pytorch version to 2.1.0 solved it for me.
