### ISSUE TITLE
URL typo in package metadata

### ISSUE THREAD

**Issue by lmmx** [Vahe1994/AQLM#21]
The package metadata on PyPI points to a repo from Vage1994 not Vahe1994

https://pypi.org/project/aqlm/

This is set in 

https://github.com/Vahe1994/AQLM/blob/48c44b18b33e0fcdef2098f2aea91c1b542f6a89/inference_lib/setup.cfg#L9

**Comment by Vahe1994** [comment]
Thanks for your fix!
