### ISSUE TITLE
Do not hard pin the `transformers` dependency version

### ISSUE THREAD

**Issue by lmmx** [Vahe1994/AQLM#22]
Hard pinning the transformers version is causing a dependency conflict in pip

https://github.com/Vahe1994/AQLM/blob/48c44b18b33e0fcdef2098f2aea91c1b542f6a89/inference_lib/setup.cfg#L35

```
Successfully built transformers
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.37.0
    Uninstalling transformers-4.37.0:
      Successfully uninstalled transformers-4.37.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aqlm 1.0.1 requires transformers==4.37.0, but you have transformers 4.38.0.dev0 which is incompatible.
Successfully installed transformers-4.38.0.dev0
```

If you change `==` to `>=` it would allow for later versions with updates (in this case, the update was for AQLM compatibility!)

**Comment by BlackSamorez** [comment]
We're waiting for a proper `transformers` `4.38.0` release to revamp the dispatch code.
Once it's released, we'll update the dependencies and model checkpoints on Hugging Face.
P.S. here's what new dispatch will look like: [Colab Example](https://colab.research.google.com/drive/1-xZmBRXT5Fm3Ghn4Mwa2KRypORXb855X?usp=sharing). No `trust_remote_code=True` and no custom `modeling_*` files needed.
