### ISSUE TITLE
Feature request: Add HF-AQLM weights on a HF org

### ISSUE THREAD

**Issue by younesbelkada** [Vahe1994/AQLM#35]
Hi there! 

Thanks again for your great work ! 

I was wondering if you would like to create a new HF org similar as: https://huggingface.co/unsloth and push the HF compatible weights there and expose a collection ? That way users could easily refer to these checkpoints as the "official" AQLM checkpoints, (e.g. `aqlm/mixtral-aqlm-2bit`, etc.)

what do you think?

cc @BlackSamorez @justheuristic

**Comment by BlackSamorez** [comment]
Hi @younesbelkada! We're planning to do it within a few days.
What would be the best course of actions to ensure people familiar with existing repos transitions to the new ones smoothly?
I was thinking about doing something funny like placing a custom code model in the old repos that would raise an error saying to use the new repos on init.

**Comment by younesbelkada** [comment]
Hi @BlackSamorez 
Good point ! 
The redirection should be automatic, I tested it out with a dummy model: https://huggingface.co/test-yblk/my-custom-bert that was previously under my namespace and:
```python
from transformers import AutoModel
model = AutoModel.from_pretrained("ybelkada/my-custom-bert")
```
worked fine. Also according to the Hub:

<img width="937" alt="Screenshot 2024-03-07 at 16 05 02" src="https://github.com/Vahe1994/AQLM/assets/49240599/60870d71-11a7-46d9-a9de-4e64a40cafa3">

So all should be good !

**Comment by BlackSamorez** [comment]
Hi @younesbelkada!
I see. I couldn't find mentions of it in the docs but yes, it's on the move page itself. 
I've moved all the models to the [`ISTA-DASLab`](https://huggingface.co/ISTA-DASLab) org on HF. That should add credibility to the checkpoints.
I'm in the process on updating the docs and examples to provide the new path where needed.

**Comment by younesbelkada** [comment]
This is great thanks @BlackSamorez ! I shared about it on HF posts here: https://huggingface.co/posts/ybelkada/546194818555981
