### ISSUE TITLE
Why only last token used in datasets for training?

### ISSUE THREAD

**Issue by VityaVitalich** [Vahe1994/AQLM#37]
Dear maintainers,

Thank you for your awesome paper and open-source project. I recently ran into the detail of dataset pre-processing, which i can not understand properly. 

In the processing of datasets you ignore all the labels exept the last one (as it is in https://github.com/Vahe1994/AQLM/blob/bf84f39c24ad1fe4eabccc22bfe9145e0c2b7d93/src/datautils.py#L51). This seems a bit odd as long as transformers perform causal masking inside forward and during training LM model we want to propagate loss through all of the tokens and not the last one.

Could you please explain this detail?

**Comment by Godofnothing** [comment]
@VityaVitalich  actually is an artifact from GPTQ code. `tar` is never used in our code (as well as in the original repository).
