### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement aqlm[gpu]==1.0.0 

### ISSUE THREAD

**Issue by safdar23** [Vahe1994/AQLM#40]
hi, I am trying to run colab_example.ipynb on NVIDIA A100 non colab environment. When i run the !pip install aqlm[gpu]==1.0.0 and getting the below message. I am using python31.0, CUDA 12.2 and NVIDIA A4 GPU

***
ERROR: Could not find a version that satisfies the requirement aqlm[gpu]==1.0.0 (from versions: 1.0.2, 1.0.3)
ERROR: No matching distribution found for aqlm[gpu]==1.0.0
****

The requirement.txt file in repo gives the below issues

ERROR: tensorflow 2.11.0 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 3.20.3 which is incompatible.
ERROR: dask-sql 2023.6.0 has requirement pandas>=1.4.0, but you'll have pandas 1.1.5 which is incompatible.
ERROR: azureml-inference-server-http 0.8.4 has requirement flask<2.3.0, but you'll have flask 2.3.2 which is incompatible.
ERROR: azureml-automl-dnn-nlp 1.51.0 has requirement datasets<=2.3.2,>=1.7.0, but you'll have datasets 2.15.0 which is incompatible.
ERROR: azureml-automl-dnn-nlp 1.51.0 has requirement torch<=1.12.0,>=1.5.0, but you'll have torch 2.2.1 which is incompatible.
ERROR: azureml-automl-dnn-nlp 1.51.0 has requirement transformers[sentencepiece]<=4.16.0, but you'll have transformers 4.37.0 which is incompatible.
ERROR: azure-cli 2.49.0 has requirement azure-keyvault-keys==4.8.0b2, but you'll have azure-keyvault-keys 4.8.0 which is incompatible.
ERROR: azure-cli 2.49.0 has requirement azure-mgmt-keyvault==10.2.0, but you'll have azure-mgmt-keyvault 10.2.1 which is incompatible.
ERROR: azure-cli 2.49.0 has requirement azure-mgmt-resource==22.0.0, but you'll have azure-mgmt-resource 21.1.0b1 which is incompatible.
ERROR: autokeras 1.0.16 has requirement tensorflow<=2.5.0,>=2.3.0, but you'll have tensorflow 2.11.0 which is incompatible.
ERROR: arviz 0.11.2 has requirement typing-extensions<4,>=3.7.4.3, but you'll have typing-extensions 4.10.0 which is incompatible.

**Comment by BlackSamorez** [comment]
Hi @safdar23 !
We deprecated the `1.0.0` version and forgot to change the example. Please use `pip install aqlm[gpu]` without specifying the version at all.

**Comment by BlackSamorez** [comment]
I've updated the notebook and verified that it works.
Thanks!
