### ISSUE TITLE
Are there any tools that can serve AQLM quantized models?

### ISSUE THREAD

**Issue by Mayorc1978** [Vahe1994/AQLM#44]
Are Ollama or other frameworks or tools capable of serving AQLM quantized models?

**Comment by BlackSamorez** [comment]
[text-generation-webui](https://github.com/oobabooga/text-generation-webui) should support it in the dev branch.
`vllm` integration is [on it's way](https://github.com/vllm-project/vllm/pull/3287) as well.

**Comment by remiconnesson** [comment]
`lorax` [on it's way too](https://github.com/predibase/lorax/issues/57#issuecomment-2002501965)
