### ISSUE TITLE
Supported Models

### ISSUE THREAD

**Issue by TechxGenus** [Vahe1994/AQLM#45]
Congratulations on coming up with such an excellent quantization algorithm! I'm trying to use AQLM to quantize Deepseek-Coder and Starcoder2, but the repository doesn't seem to have direct support. Are there any plans to support more models? Or any suggestions on how to modify the source code to achieve fast support, thanks.

**Comment by BlackSamorez** [comment]
Hi! Only a minor modification is needed to be able to run a different model architecture.
Hopefully, a change [like this](https://github.com/Vahe1994/AQLM/commit/f50fca6a21131f61d2570317e611b5a9f4e8ca19) should be enough to run `starcoder2`. You can try it out in the `starcoder2` branch.

**Comment by TechxGenus** [comment]
Thanks!
