### ISSUE TITLE
How model_seqlen affects quantization quality

### ISSUE THREAD

**Issue by VirtualRoyalty** [Vahe1994/AQLM#46]
Hi!
Thanks for such a useful tool!
I have a question about `model_seqlen`:

As I can see default value in main.py is 4096. What if I'll use a smaller values e.g. 1024 when quantizing MoE mixtral model? Will it affect the quality of quantized model? Or quality on greater than 1024 contexts? Will it significantly speedup process of quantization?

Thanks in advance!

```python
    parser.add_argument(
        "--model_seqlen",
        type=int,
        default=4096,
        help="Model seqlen and calibration data context length.",
    )
```

**Comment by BlackSamorez** [comment]
Hi! It is recommended to use the seq_len the model you're quantizing was trained on (4096 for Llama-2, 8192 for mistral/mixtral). To reduce the number of samples, speeding up computations, you should decrease `--nsamples ` instead.
However, it doesn't have that large impact on the quantization time anyway.

**Comment by VirtualRoyalty** [comment]
@BlackSamorez Thanks for the answer

I am trying to quantize finetuned version of mixtral and I had no such long samples (8192) in training set.

Then should I decrease max_epochs and finetune_max_epochs instead (in order to speedup the process)?

**Comment by Godofnothing** [comment]
@VirtualRoyalty you may try and see how shorter sequences affect the quality. When I was tuning Mixtral, i used 7k instead of 8k to fit into memory and this seems to work fine. However, 1k is much shorter than 8k, so I cannot say apriori, whether it matters much.

**Comment by VirtualRoyalty** [comment]
@Godofnothing Thanks, good point!
