### ISSUE TITLE
33B llama quantization post-inference time

### ISSUE THREAD

**Issue by ACoder-J** [Vahe1994/AQLM#56]
Why is it that after I quantize, my inference is 2 times slower than the original `model?

`Quantize command：python main.py $MODEL_PATH $DATASET_PATH --nsamples=1024 --num_codebooks=1 --nbits_per_codebook=16 --in_group_size=8 --relative_mse_tolerance=0.01 --finetune_relative_mse_tolerance=0.001 --finetune_batch_size=32 --local_batch_size=1 --offload_activations --wandb --save $SAVE_PATH --dtype float32`

Quantitative results：
![image](https://github.com/Vahe1994/AQLM/assets/11597706/1bc41c17-8626-4b9c-b5ba-87f7734c898f)

In addition, looking at the GPU usage, it seems that it has become a parallel pipeline. I use four cores to load the model, but only one GPU utilization is 100% at the same time.
![image](https://github.com/Vahe1994/AQLM/assets/11597706/87ed8f71-d98c-464c-8568-4d0f101f6962)

Have you encountered the same problem as me again? Is the inference speed of your quantized model normal?

**Comment by BlackSamorez** [comment]
Hi @ACoder-J !
The inference speed is really bottlenecked by `transformers` for multiple reasons (transformers being slow and kernel launches taking long).
One way to achieve proper speedup is to compile your model into a cuda graph. It's a new feature added to _PyTorch_ in `2.0.0` and refined in `2.2.1`. People of `transformers` have also been working hard to properly support and [document](https://github.com/huggingface/transformers/pull/29791) it. To check out what you can do with it already, please refer to [this AQLM demo](https://github.com/Vahe1994/AQLM/blob/main/notebooks/aqlm_cuda_graph.ipynb).
Another way to properly serve AQLM is to use the [vllm integration](https://github.com/vllm-project/vllm/pull/3287). It's not complete yet but it might be usable already (not sure).
