### ISSUE TITLE
AQLM support for Cohere Command-R +

### ISSUE THREAD

**Issue by Mayorc1978** [Vahe1994/AQLM#67]
Considering is probably the best OS LLM model at the moment, an optimized AQLM model would be great.

**Comment by BlackSamorez** [comment]
We're working on it. If we're lucky, we'll publish both Command-R and Command-R+ quantizations within 4-5 days.

**Comment by BlackSamorez** [comment]
`Command-R` is complete. You can find [the model on the hub](https://huggingface.co/ISTA-DASLab/c4ai-command-r-v01-AQLM-2Bit-1x16).
`Command-R+` will most likely be done in a few days.

**Comment by BlackSamorez** [comment]
`Command-R+` is complete as well. You can find [the model on the hub](hhttps://huggingface.co/ISTA-DASLab/c4ai-command-r-plus-AQLM-2Bit-1x16).
