### ISSUE TITLE
Quantization time & VRAM requirements

### ISSUE THREAD

**Issue by oobabooga** [Vahe1994/AQLM#8]
Hello,

I have two basic questions:

1) Do you have any data on how long it takes to quantize a 70b model using 24GB VRAM (assuming that's possible)?
2) Do you plan to release prequantized models on Hugging Face? Having llama-2-70b for comparison with other methods would be useful.

**Comment by Vahe1994** [comment]
Hello!
1. With current code(without any major changes), I don't think LLama-2 70B model will fit into 24GB VRAM, for quantization phase. 
2. Yes, we are planing to do so.

**Comment by Vahe1994** [comment]
Hi!
@oobabooga  we just released quantized models on Hugging Face , see Readme.md (including LLama-2 70B). Please see notebooks(for streaming or generation) for examples how to use it. Hope this helps.
