### ISSUE TITLE
Request: Phi-3-mini-128k-instruct Support

### ISSUE THREAD

**Issue by vackosar** [Vahe1994/AQLM#83]
Hello,

Phi-3 is a small (3.8b) but well known and quite a useful model based on evals and my prompting.

Would it be possible to quantize Phi-3? There is also 4k version of the model.

HF: https://huggingface.co/microsoft/Phi-3-mini-128k-instruct
HF 4k: https://huggingface.co/microsoft/Phi-3-mini-4k-instruct

Thank you very much,
Vaclav

**Comment by Godofnothing** [comment]
Hi, @vackosar, yeah, we can quantize these models. 

However, these models have quite large embedding matrices and the current version of our code allows compressing only weight matrices in transformer blocks, limiting the level of possible compression. Hence, I would expect that the resulting model size would be somewhere in between 2 and 3 Gb. 

In the future, we intend to add embedding and language modelling head compression.

**Comment by Godofnothing** [comment]
@vackosar 
Here they are:
- https://huggingface.co/ISTA-DASLab/Phi-3-mini-128k-instruct-AQLM-1x16
- https://huggingface.co/ISTA-DASLab/Phi-3-mini-4k-instruct-AQLM-1x16
