### ISSUE TITLE
Query on Evaluation Support for C4 Validation

### ISSUE THREAD

**Issue by ShunLu91** [Vahe1994/AQLM#84]
Thanks for the excellent work and I really appreciate the public code.

I am currently working with the `lm-evaluation-harness` for validating some of the language models and have encountered a slight issue. It appears that the `lm-evaluation-harness` does not provide support for validation on the C4 dataset.

I was wondering if you might have any recommendations or alternative approaches for conducting validation on the C4 dataset using the `lm-evaluation-harness` or similar tools. Your guidance on this matter would be greatly appreciated.

Thank you once again for your contribution to the community. I am looking forward to your response.

**Comment by Vahe1994** [comment]
Hello!
Thank you for your interest in the work. 
In the main.py there is a code for  calculating ppl on c4 validation dataset https://github.com/Vahe1994/AQLM/blob/0e57afbb89c8af05ca5a343f11754705255c8163/main.py#L896. Is this what you are looking for?

**Comment by ShunLu91** [comment]
Thanks for your timely reply. 
After running the `main.py` using the `no_quant` mode, I noticed that only 256 samples were sampled to calculate the ppl on c4 validation dataset.
As I want to reproduce the baseline result 6.63 of c4 in the first row of your Tables 1 & 2, I wonder how to modify the sampling code in `get_c4()` function of the `datautils.py`.

**Comment by ShunLu91** [comment]
Dear authors, 
By using the `no_quant` mode to evaluate  Llama-2-7b-hf and Mistral-7B models, I got the following results:
- Llama-2-7b-hf (model_seqlen=4096, no_quant) ppl=6.63, which is consistent with the results in the paper. 
- Mistral-7B (model_seqlen=8192, no_quant) ppl=6.94. It is weird that Mistral-7B performs worse than Llama-2-7b-hf and is inconsistent with the result 5.71 reported in your Table.17. I present the command as below and can you help me to figure out the difference?
```Shell
export CUDA_VISIBLE_DEVICES=4,5,6,7  # optional: select GPUs
export MODEL_PATH=pretrained/Mistral-7B # Llama-2-7b-hf
export DATASET_PATH=dataset/c4
export SAVE_PATH=None


python main.py $MODEL_PATH $DATASET_PATH \
        --model_seqlen=8192 \ #  4096 for Llama-2
        --nsamples=1024 \
        --val_size=128 \
        --num_codebooks=1 \
        --nbits_per_codebook=16 \
        --in_group_size=8 \
        --relative_mse_tolerance=0.01 \
        --finetune_batch_size=32 \
        --finetune_max_epochs=0 \
        --finetune_early_stop=3 \
        --finetune_keep_best \
        --local_batch_size=1 \
        --offload_activations \
        --no_quant \
        --save $SAVE_PATH
```

**Comment by Vahe1994** [comment]
Hello!
Sorry for the late answer. We are calculating ppl on a split of c4. The code comes from [GPTQ](https://github.com/IST-DASLab/gptq/blob/2d65066eeb06a5c9ff5184d8cebdf33662c67faf/datautils.py#L54). 

Regarding different ppl score on c4. I'm not sure why you are getting 6.94ppl. I rerun the ppl calculation and got  5.646. Although it is a little bit off(probably something slightly changed in either model,data or dependencies), it is not that much.
Can you please check are you using Mistral-7B-v0.1 or instruct version?
Can you please try to run the code from main branch with this command:
``` CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=16 MKL_NUM_THREADS=16  python main.py "mistralai/Mistral-7B-v0.1"  "pajama" --max_epochs=15 --nsamples=256 --num_codebooks=1 --nbits_per_codebook=15 --in_group_size=8 --scale_nbits=0 --model_seqlen=8192 --offload_activations --no_quant```

**Comment by ShunLu91** [comment]
Thanks for your advice. I have achieved the right ppl score by fixing the version of Mistral-7B-v0.1.
