### ISSUE TITLE
Minor race condition in CPU 2x8 inference code

### ISSUE THREAD

**Issue by justheuristic** [Vahe1994/AQLM#86]
The current implementation sometimes returns close_but_not_very_accurate outputs because of this line:

https://github.com/Vahe1994/AQLM/blob/main/inference_lib/src/aqlm/inference_kernels/numba_kernel.py#L43

This is because the cpu cores may  concurrently write to the same output unit without atomic addition.

Changing the outer parallel loop to go over output_groups instead fixes the issue, but it may be slower.
Note that the layer error is within <1% in my experiments and the model outputs look reasonable.

@BlackSamorez , would the code be any slower if you change the summation to go in parallel over outer groups or use atomic addition?

**Comment by Vahe1994** [comment]
This issue is still valid.
