### ISSUE TITLE
Finetuning ISTA-DASLab/Mistral-7B-Instruct-v0.2-AQLM-2Bit-2x8: RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by tehohep1** [Vahe1994/AQLM#87]
I've tried to finetune the model "ISTA-DASLab/Mistral-7B-Instruct-v0.2-AQLM-2Bit-2x8" using the notebook "aqlm_2bit_training.ipynb" but I get the below runtime error after initiating the training. Before trying to finetune this model, I had successfully run this notebook with the original model "ISTA-DASLab/Mixtral-8x7b-AQLM-2Bit-1x16-hf" that was defined in the notebook.

ERROR:
"
max_steps is given, it will override any value given in num_train_epochs
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-5-388f70847b39>](https://localhost:8080/#) in <cell line: 24>()
     22 )
     23 model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
---> 24 trainer.train()

34 frames
[/usr/local/lib/python3.10/dist-packages/torch/_ops.py](https://localhost:8080/#) in __call__(self, *args, **kwargs)
    753         # We save the function ptr as the `op` attribute on
    754         # OpOverloadPacket to access it here.
--> 755         return self._op(*args, **(kwargs or {}))
    756 
    757     # TODO: use this to make a __dir__

RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions."

**Comment by justheuristic** [comment]
Hi! It look like we missed this one in the NeurIPS craze. If the issue is still relevant, please comment something
