### ISSUE TITLE
Actual bitrate of models on github?

### ISSUE THREAD

**Issue by tsengalb99** [Vahe1994/AQLM#88]
Are the models you report in your readme supposed to be actual 2 bit models or just 2.x bit models? For example, the two 7B models below are both larger than a 2 bit decoder model, which would take 2.1G on disk. Also, why is there such a large difference in size between the 1x16 and 2x8 models? The size gap is much larger than the codebook size delta should take. Are you using different groupsizes in each model? Thanks

![image](https://github.com/Vahe1994/AQLM/assets/33385672/a08120fa-2f2c-438d-9cf5-cc9aeee8de23)

**Comment by BlackSamorez** [comment]
@tsengalb99 
We are not. We use row-wise scales and offsets. 8 is a vector quantization group size.
