### ISSUE TITLE
Request for the Llama-2-13B with AQLM (2x8 scheme)

### ISSUE THREAD

**Issue by ChenMnZ** [Vahe1994/AQLM#90]
Hello,

Thanks for your outstanding works. I want to do a compressive comparison of recent quantization methods. 

Due to that latest lm-eval can obtain higher accuracy than the ones reported in paper, I have to re-evaluate each quantized models.

I found that there is not model about  Llama-2-13B with AQLM (2x8 scheme), can you share it on huggingface?

Thank you!

**Comment by Vahe1994** [comment]
Hello! 
Sorry for late response. It was very busy several weeks. 
Thanks for interest in the work. Currently 13B 2x8gs8 quantization is running. When it is done, I will put it in HF hub and tell you.

P.s. Additionally you can check out this PR https://github.com/Vahe1994/AQLM/pull/93 for new LM eval code. Thanks to  fast dequantization kernels,  you can run lm eval from HF as any other models. 
For ppl please check out https://github.com/Vahe1994/AQLM/issues/91.

**Comment by Vahe1994** [comment]
@ChenMnZ The model is ready please see https://huggingface.co/ISTA-DASLab/Llama-2-13b-AQLM-2Bit-2x8-hf

**Comment by ChenMnZ** [comment]
Thanks for your time!!! I will try this model.

**Comment by ChenMnZ** [comment]
Thanks for your time!!! I will try this model.
