### ISSUE TITLE
How to run perplexity eval on HF hub models?

### ISSUE THREAD

**Issue by tsengalb99** [Vahe1994/AQLM#91]
Hi, what command should I run in your codebase to get perplexity numbers on wikitext and c4 for your HF hub models (eg https://huggingface.co/ISTA-DASLab/Meta-Llama-3-70B-AQLM-2Bit-1x16/tree/main)

**Comment by Godofnothing** [comment]
Hi, @tsengalb99. 

Currently, the approach used in the recent evals is quite dirty.

- Clone [this repository](https://github.com/Godofnothing/aqlm-evaluation-harness)
- Specify evals (`arc_easy`, `mmlu`, whatever)
- Specify the path to AQLM repository `aqlm_src_path`  and the checkpoint in the format produced in `main.py` as follows: `pretrained=$MODEL_PATH,aqlm_checkpoint_path=$CHECKPOINT_PATH,aqlm_src_path=$AQLM_SOURCE_CODE_PATH`
- Run the script below.

```
lm_eval --model hf \
    --model_args pretrained=$MODEL_PATH,aqlm_checkpoint_path=$CHECKPOINT_PATH,aqlm_src_path=$AQLM_SOURCE_CODE_PATH,parallelize=True,dtype=float16 \
    --tasks winogrande,piqa,hellaswag,arc_easy,arc_challenge \
    --batch_size 8
```

For our evals we adopted `lm_eval=4.0.0`. 
It should work with AQLM converted checkpoints, hosted on the hub, as well. But runtime is typically slower, especially for large batch sizes.

**Comment by Godofnothing** [comment]
Hi, @tsengalb99. Sorry for delayed reply.

It is fairly easy:

```bash
python main.py \
  ISTA-DASLab/Meta-Llama-3-70B-AQLM-2Bit-1x16 \
  wikitext2 \ # dummy dataset
 --model_seqlen 8192 \
 --no_quant
```
